### PR TITLE
Created guides for crash analytics

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
Awesome @AltamashShaikh 

I’ve slightly updated the menu structure so it’s similar to others and what was planned initially. Also added the file to the menu so it actually appears in the menu. Also added the section `Tracking HTTP API Reference` to https://developer.matomo.org/api-reference/tracking-api

There’s a few links not working in the initial “home” page of crash analytics like user guide, FAQ, and the plugin link goes to crash-analytics.net.

I haven’t double checked the content. We may need to look over it that it all makes sense and that the method names and HTTP parameter names are still correct and that formatting is good.

Realising though that the DB structure is still missing. This we may need to add and at least have the tables and columns there https://developer.matomo.org/guides/database-schema . I can potentially help fill in the blanks

**Comment by AltamashShaikh** [comment]
@tsteur Added the schema for crash-analytics

**Comment by tsteur** [comment]
Awesome, thanks @AltamashShaikh  looks good 👍

**Comment by AltamashShaikh** [comment]
@tsteur I am merging this, we can refine it as we progress

**Pull request merged**
