### PR TITLE
Use system fonts

### PR DESCRIPTION
**Pull request by tsteur**
For consistency with Piwik 3. Makes the site load faster and not flickr anymore. Always took a while to load all the fonts etc. Also looks better IMO

### CODE REVIEW

**Comment by lipis** [comment]
Yes please!

**Comment by tsteur** [comment]
ping @mattab

**Comment by mattab** [comment]
Of course :+1:

**Comment by lipis** [comment]
and it's already live?! That's nice..

**Comment by mattab** [comment]
Yes: continuous deployment FTW

**Pull request merged**
