### PR TITLE
Document updating the plugin bundles

### PR DESCRIPTION
**Pull request by snake14**
### Description:

Document updating the plugin bundles so that we remember next major release.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — COMMENTED** [review]
@snake14 Looks good, I added a comment [here](https://github.com/innocraft/PremiumBundle/commit/a40f4c135cd8e47e6f4b162a3784aa165ecf9f20#r124611175) w.r.t this change

**Comment by michalkleiner** [comment]
I'm sitting on the fence whether this should be part of the open source documentation. It feels like it should go to internal docs, but at the same time it's a one-liner that might actually bring attention to the premium plugins in general.

What do you reckon @sgiehl?

**Comment by snake14** [comment]
@michalkleiner This is the page in which Thomas told me to add it, which makes sense since this is where we document the major release process. I can move it if you think it's better suited somewhere else, though.

**Comment by sgiehl** [comment]
Guess should be fine to add that here

**Review by michalkleiner — APPROVED** [review]

**Pull request merged**
