### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by t3chguy**

### CODE REVIEW

**Comment by sgiehl** [comment]
Thanks for the PR. There is actually the same typo in Piwik. I've proposed a PR for that.
Btw. the same typo still exists in line 414

**Comment by t3chguy** [comment]
@sgiehl are you sure?
> Both `checkOnScroll` and `timeIntervalInMs` cannot be changed after this method was called the first time.

**Comment by sgiehl** [comment]
sorry, checked that on my local copy. Guess I forgot to pull ;)

**Comment by mattab** [comment]
Thanks for the PR @t3chguy - appreciated :+1:

**Pull request merged**
