### PR TITLE
Add ER diagram screenshot, #PG-3667

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Adds ER diagram screenshot
Fixes: #PG-3667

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by adamreng — CHANGES_REQUESTED** [review]
A new user would probably find it helpful to see this diagram near the top of the page. Should we consider moving this section before the "Log data" section?

**Review by snake14 — APPROVED** [review]
Looks good to me :+1:

**Review by adamreng — APPROVED** [review]
Liking the diagram at the top of the page. Looks good to me too 👍

**Review by snake14 — APPROVED** [review]
Looks good :+1:

**Comment by michalkleiner** [comment]
I've left a comment on the internal JIRA ticket about the missing relations.

**Comment by michalkleiner** [comment]
@sgiehl you reckon this is good to be merged or are there any objections?

**Comment by sgiehl** [comment]
> @sgiehl you reckon this is good to be merged or are there any objections?

Hm. The diagram lacks the archive_numeric & archive_blob tables, though their names are dynamic.

In addition I wonder how this chart will be kept up to date. We don't have any processes around that, so it most likely will be outdated directly after the next database change we need to add. I wonder if we could have any automated process to generate such a chart. We could then use a GitHub action to automatically update it when it changes...

**Comment by adamreng** [comment]
@sgiehl Agreed, we should add those two entities as archive_numeric_{year}{month} and archive_blob{year}_{month} (or archive_numeric_yyyy_mm, though I lean towards the former format).

For updates, we're trying to maintain a narrow scope for this ticket. That's also why we haven't added relationship lines for implied foreign keys.

Do we have a checklist for major releases? In the checklist, we could add an item to either update the diagram or create a ticket to update it.

Alternatively, we could add a "Last updated on [date] for Matomo version X.X.X" note with the diagram.

If these suggestions don't fully address the concern, we can consider other options or potentially expand the ticket's scope. In any case, I believe even an occasionally outdated diagram provides significant value compared to having no diagram at all.

**Comment by AltamashShaikh** [comment]
@sgiehl @michalkleiner I have added the archive tables and renamed it to "Entity Diagram" and also mentioned the core version as a note.

**Review by snake14 — APPROVED** [review]
Looks good to me. Nice addition of a few archive tables :+1:

**Comment by sgiehl** [comment]
I guess it would be better to only have one archive table of each type in the diagram, but with a name containing placeholders, like @araichyk suggested. That would make it more clear that those tables are dynamically created.

**Comment by AltamashShaikh** [comment]
@sgiehl @michalkleiner 
changed the DB to pull data from `v5.1.0` and changed the name of archive tables to archive_{blob/numeric}_{year}_{month}

**Review by sgiehl — APPROVED** [review]
Guess this in general looks good now.
Personally I likely would have tried to sort the tables either alphabetically or by scope (archives, logs, users, sites, ...), as it currently isn't easy to find what you are looking for.

**Pull request merged**
