### PR TITLE
Documentation on composer requirements

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

We currently actually didn't really have some process for updating our composer dependencies.

I've created a new GitHub action in https://github.com/matomo-org/matomo/pull/17969 to automate minor & patch release updates.

For major updates we actually need to find a proper solution. Maybe another action could create issues if major updates are available, so we see that updates are available. Another option would be some kind of recurring task every X months to check for updates.

Might be good to discuss that, so we can adjust this documentation accordingly.

Let me know if anything else should be changed or is maybe missing.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
@sgiehl can you add this guide to a menu item see https://github.com/matomo-org/developer-documentation#adding-the-new-guide-to-a-menu-item and then merge?

**Comment by sgiehl** [comment]
@tsteur I've added it to the menu. Not sure if we should already merge it. It mentions and links an action which will be available after merging https://github.com/matomo-org/matomo/pull/17969, so merging this PR now, might introduce broken links

**Comment by tsteur** [comment]
Looks like it's only one link? We could still merge or just remove that link and then merge.

**Comment by geekdenz** [comment]
Seems good to merge from my pov.

**Comment by sgiehl** [comment]
Removing the link only doesn't make much sense. The docs are describing a process that is available after https://github.com/matomo-org/matomo/pull/17969 was merged. Reviewing that one should be quite simple, as the action isn't doing much. Afterwards we can directly merge this one.

**Pull request merged**
