### PR TITLE
add note about MDN

### PR DESCRIPTION
**Pull request by diosmosis**
personally I find it more useful than caniuse

### CODE REVIEW

**Comment by Findus23** [comment]
Just FYI: caniuse now also uses MDN data, so you can now also find compatibility data for very specific funktions (e.g. https://caniuse.com/mdn-api_domtokenlist_contains) there.

**Comment by tsteur** [comment]
👍  LGTM. BTW @diosmosis curious where the information is more granular or what you mean there? Just FYI the reason I use ICanUse is that you can easily search for anything and see the information directly without needing to scroll or click around. And you can filter and show different visualisations when needed etc.

**Comment by diosmosis** [comment]
@tsteur it's been quite a while since i've had to look something up, but generally if I want to know if a specific function is usable on a specific browser (eg, Array.find), MDN makes it easier since the docs for that specific method will say so (the same for node attributes, language features, etc.). W/ caniuse (in the past at least), a search would lead to "Array functions" or something generic, and I wouldn't necessarily know if the specific thing I was looking for was included.

**Comment by tsteur** [comment]
Thanks @diosmosis

**Pull request merged**
