### PR TITLE
For Matomo Tag Manager users, reading the JS Tracker reference, suggest the correct approach

### PR DESCRIPTION
**Pull request by mattab**

### CODE REVIEW

**Review by AltamashShaikh — APPROVED** [review]
Good to roll back this info

**Review by snake14 — APPROVED** [review]
With the idea that we want these developer docs to be strictly customer facing, these changes make sense. The same changes will need to be made to the 4.x documentation as well.

Does everything look alright to you @AltamashShaikh ? I updated the Jira issue created to follow-up on the MTM `_paq` changes to include adding an inline comment in the core JS tracker so that core devs know that tracker configurations need to be added to MTM as well. We also have a wiki page. It was referring to this page, but I copied the content into the wiki page.

**Comment by AltamashShaikh** [comment]
@snake14 Now did you mention it, we should update the doc for `4.x-dev` branch too

**Comment by snake14** [comment]
> @snake14 Now did you mention it, we should update the doc for `4.x-dev` branch too

Thanks @AltamashShaikh . If the changes look good, I can make the same changes to 4.x as well.

**Comment by AltamashShaikh** [comment]
> > @snake14 Now did you mention it, we should update the doc for `4.x-dev` branch too
> 
> Thanks @AltamashShaikh . If the changes look good, I can make the same changes to 4.x as well.

Yes go ahead

**Pull request merged**
